**Hello everyone!**

This assignment is based on basics of python and then gradually moves on to the python libraries required for working in ML.

**Workflow**

Above each cell there are some instructions and resources (wherever necessary) for completing the question. You are supposed to solve the questions in the cells below the question text, feel free to add cells if you want.

Note: All the documentations provided are very extensive and you do not need to know everything but you are expected to be able to refer to them as and when required.


# Basic Python

If you are absolutely new to python, quickly go through this video: https://www.youtube.com/watch?v=K5KVEU3aaeQ&ab_channel=ProgrammingwithMosh

This will help you brush up your python to get your started.


# Part A



**Q.1**

 Create an array of 10 zeros.
Create an array of 10 fives.
 Create a 3x3 matrix with values ranging from 0 to 8
Use NumPy to generate a random number between 0 and 1
Create an array of 20 linearly spaced points between 0 and 1
  Write a program that counts how many vowels are in a string.





1.   Create an array of 10 zeros.
2.   Create an array of 10 fives.
3.   Create a 3x3 matrix with values ranging from 0 to 8
4.   Use NumPy to generate a random number between 0 and 1
5.   Create an array of 20 linearly spaced points between 0 and 1
7.   Write a program that counts how many vowels are in a string.





In [ ]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#Q.1.2
k = np.ones(10)
k = k*5

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
mat_3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(mat_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
rdi = np.random.random()
print(rdi)

0.917415254734327


In [ ]:
lspa = np.linspace(0,1,20)
print(lspa)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
#Just for a thing , I am assuming my own string to test on
s = "Trying BCS judge it well assignment"
vow_count = 0
vowel_list = 'AEIOUaeiou'
for i in range(0,len(s)):
  if (s[i] in vowel_list):
   vow_count += 1
print(vow_count)

8


**Q.2**


1.   Extract the even numbers from this array using slicing.
2. Create a 2D array with 5 rows and 4 columns, filled with random integers between 10 and 100.
3. Extract a 3x2 subarray from the 2D array (e.g., first three rows, first two columns).
4. Reshape the 1D array of integers into a 4x5 2D array.
5. Flatten the 2D array back to a 1D array and print it.
6. Perform matrix multiplication between two 2D arrays (you can generate the second 2D array randomly).



In [ ]:
numbers = [12,7,44,19,102,-8,33,56,77,90,121,-24,48]
even_count = 0
for i in range(0,len(numbers)):
  if(numbers[i]%2==0):
    even_count += 1
print(even_count)

8


In [ ]:
rand_arr = np.random.randint(10,100,size=(5,4))
print(rand_arr)

[[99 68 79 18]
 [47 72 10 61]
 [47 20 37 14]
 [63 89 55 10]
 [62 69 44 40]]


In [ ]:
sub_arr = rand_arr[[0,1,2]][:,[0,1]]
print(sub_arr)

In [82]:
arr = np.random.randint(1,100,size=(20,1))
arr = arr.reshape(4,5)
arr

array([[26, 75, 28, 10, 26],
       [ 6, 22, 28, 79, 56],
       [39, 97,  5, 84, 50],
       [22, 55, 53, 28, 13]])

In [83]:
arr = arr.ravel()
arr

array([26, 75, 28, 10, 26,  6, 22, 28, 79, 56, 39, 97,  5, 84, 50, 22, 55,
       53, 28, 13])

In [85]:
def mat_mult(A,B):
  rtr = np.zeros((A.shape[0],B.shape[1])) # Corrected initialization for a 2D array of zeros
  for i in range(0,A.shape[0]):
    for j in range(0,B.shape[1]):
      for k in range(0,A.shape[1]):
        rtr[i][j] += (A[i][k])*(B[k][j])
  return rtr
arr1 = np.random.randint(1,100,size=(5,4))
arr2 = np.random.randint(1,100,size=(4,5))
mat_mult(arr1,arr2)

array([[ 6977.,  5365.,  4404.,  3569.,  4402.],
       [ 7357.,  3007.,  6460.,  6231.,  3782.],
       [19844.,  9234., 15274.,  7696., 10786.],
       [ 9347.,  8443.,  9268.,  4827.,  8602.],
       [13855.,  9891., 12705.,  6654., 10631.]])

**Q.3**

(i) Check if matrix multiplication is valid

In [87]:
def isValid(A,B):
  if A[1] == B[0]:
    print(" Valid")
  else :
    print("Invalid")

(ii) Using loops (without using numpy)

In [88]:
def mat_mult(A,B):
  rtr = np.zeros((A.shape[0],B.shape[1])) # Corrected initialization for a 2D array of zeros
  for i in range(0,A.shape[0]):
    for j in range(0,B.shape[1]):
      for k in range(0,A.shape[1]):
        rtr[i][j] += (A[i][k])*(B[k][j])
  return rtr
arr1 = np.random.randint(1,100,size=(5,4))
arr2 = np.random.randint(1,100,size=(4,5))
mat_mult(arr1,arr2)

array([[12112., 13924., 14897.,  8907., 14594.],
       [ 9152., 11494.,  8592.,  5476., 12070.],
       [15751., 17964., 15678.,  9676., 16777.],
       [ 6754.,  8392., 10038.,  4587.,  9873.],
       [ 4144.,  5014.,  4515.,  1701.,  4776.]])

**Q.4**
(i) Given:

In [90]:
X = [1,2,3,4,5]
y = [2,4,5,4,5]

In [110]:
mx = np.mean(X)
my = np.mean(y)
print(mx)
print(my)
#since I am getting no clue of what the slope and intercept really mean , I am going to apply simple linear regression model
m = 0
b = 0
def grad_desc(X,y,L,m,b):
  m_desc = 0
  b_desc = 0
  for i in range(0,len(X)):
    m_desc += -2*X[i]*(y[i]-(m*X[i]+b))
    b_desc += -2*(y[i]-(m*X[i]+b))
  m = m - L*m_desc
  b = b - L*b_desc
  return m,b
for i in range(0,1000000):
  m,b = grad_desc(X,y,0.0001,m,b)
print(m)
print(b)
print("predicted Y for 6 : ",m*6+b)
print("predicted Y for 7 : ",m*7+b)


3.0
4.0
0.6000000000003606
2.1999999999986963
predicted Y for 6 :  5.80000000000086
predicted Y for 7 :  6.400000000001221


Compute:

mean of X

mean of y

slope (m)

intercept (c)

predicted values

No libraries allowed.(sklearn or numpy)


##  Pandas


csv file:- https://drive.google.com/file/d/1Q4bT1VNcZFY-tA3x3BV8MwqezuhqVFLq/view?usp=sharing


**Perform the following operations on the csv file:**

1. Read the csv into a pandas dataframe and back it up (you will thank yourself for doing this when you mess up something while manipulating the dataframe).
2. Explore the dataframe (find out the different ways you can do this).
3. Play around with each column of the dataframe and figure out ways to modify them according to your needs.
4. Read up on ``iloc`` and demonstrate it on the dataframe.
5. Handle ``null`` values in the dataframe.
6. Try dropping rows/columns.
7. Filter rows where a string column starts with a specific letter.
8. Create a new column as a combination of two existing columns (this is feature engineering which you may use in your ML journey).